server:
  port: 8888

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: 2019214081
    password: 2019214081
    url: jdbc:mysql://123.57.27.150:3306/2019214081
    type: com.zaxxer.hikari.HikariDataSource
